joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
front:
    type: velocity_controllers/JointVelocityController
    joint: rim_front_joint
    pid: {p: 0.00, i: 0.0, d: 0.0}
rear:
    type: velocity_controllers/JointVelocityController
    joint: rim_rear_joint
    pid: {p: 0.00, i: 0.0, d: 0.0}
left:
    type: velocity_controllers/JointVelocityController
    joint: rim_left_joint
    pid: {p: 0.00, i: 0.0, d: 0.0}
right:
    type: velocity_controllers/JointVelocityController
    joint: rim_right_joint
    pid: {p: 0.00, i: 0.0, d: 0.0}
    
